apiVersion: v1
kind: Service
metadata:
  name: filemaker-service
spec:
  selector:
    app: filemaker
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filemaker
spec:
  selector:
    matchLabels:
      app: filemaker
  replicas: 1
  template:
    metadata:
      labels:
        app: filemaker
    spec:
      containers:
      - name: filemaker
        image: filemaker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: ENVIRONMENT
            value: "qa"
          - name: BUCKET_NAME
            value: "rcarson-inra-test"
          - name: AWS_REGION
            value: "eu-west-1"
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: codechallenge-secrets
                key: access_key
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: codechallenge-secrets
                key: secret_access_key
